#!./venv/bin/python

from format_gcc_output import format_gcc_output



command = ['g++', '-Wall', '-Wextra', '-fdiagnostics-format=json', '-o', 'test2', 'test2.cpp']
format_gcc_output (command)


command = ['gcc', '-Wall', '-Wextra', '-fdiagnostics-format=json', '-o', 'test1', 'test1.c']
format_gcc_output (command)


# Make example call
#command = ['make', 'dev']
#format_gcc_output (command)


